---
# file: roles/download-debian/tasks/main.yml

- name: download debian 11.3.0 Bullseye
  become: yes
#  get_url:
#    url: https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.3.0-amd64-netinst.iso
#    dest: /var/lib/libvirt/images/debian-11.3.0-amd64-netinst.iso
#    checksum: sha512:2810f894afab9ac2631ddd097599761c1481b85e629d6a3197fe1488713af048d37241eb85def681ba86e62b406dd9b891ee1ae7915416335b6bb000d57c1e53
  copy:
    src: debian-11.3.0-amd64-netinst_custom.iso
    dest: /var/lib/libvirt/images/debian-11.3.0-amd64-netinst_custom.iso
